apiVersion: v1
kind: Pod
metadata:
  name: esempio-emptydir
spec:
  volumes:
    - name: homedir
      emptyDir: {}
  containers:
    - name: webserver
      image: httpd:2.4
      volumeMounts:
        - name: homedir
          mountPath: /usr/local/apache2/htdocs
    - name: generatore-homepage
      image: alpine
      volumeMounts:
        - name: homedir
          mountPath: /output
      command: ["/bin/sh"]
      args: ["-c", "echo '<h1>Benvenuti sul nostro sito!</h1>' > /output/index.html"]